# Generated by Django 4.2.2 on 2023-06-27 00:56

import apps.adocao.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_endereco_is_principal_alter_endereco_complemento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('adotado', models.BooleanField(default=False, verbose_name='Adotado')),
                ('avatar', models.ImageField(upload_to=apps.adocao.models.upload_to_animal_photos, verbose_name='Avatar')),
                ('idade', models.CharField(blank=True, choices=[('ate_1_ano', 'Até 1 ano'), ('um_a_tres_anos', '1 a 3 anos'), ('tres_a_cinco_anos', '3 a 5 anos'), ('cinco_a_dez_anos', '5 a 10 anos'), ('dez_a_quinze_anos', '10 a 15 anos'), ('quinze_a_vinte_anos', '15 a 20 anos')], default=None, max_length=20, verbose_name='Idade')),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default=None, max_length=10, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('cor_olho', models.CharField(max_length=20, verbose_name='Cor do olho')),
                ('sobre', models.TextField(verbose_name='Sobre')),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='OutrasCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.tipoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=apps.adocao.models.upload_to_animal_photos, verbose_name='Foto')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalResgate',
            fields=[
                ('data_resgate', models.DateField(primary_key=True, serialize=False, verbose_name='Data do resgate')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.animal')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='comandos',
            field=models.ManyToManyField(blank=True, to='adocao.comando'),
        ),
        migrations.AddField(
            model_name='animal',
            name='outras_caracteristicas',
            field=models.ManyToManyField(blank=True, to='adocao.outrascaracteristica'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.raca'),
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateTimeField(auto_now_add=True, verbose_name='Data da adoção')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data do início da adoção')),
                ('etapa', models.CharField(choices=[('entrevista', 'Entrevista')], default='entrevista', max_length=20, verbose_name='Etapa da adoção')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.animal')),
            ],
            options={
                'unique_together': {('animal', 'adotante')},
            },
        ),
    ]
