# Generated by Django 4.2.2 on 2023-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_alter_animal_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adocao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='etapa',
            field=models.CharField(choices=[('requisicao_realizada', 'Requisição Realizada'), ('entrevista_presencial', 'Entrevista Presencial'), ('finalizado_adocao_realizada', 'Finalizado - Adoção Realizada'), ('finalizado_adocao_rejeitada', 'Finalizado - Adoção Rejeitada')], default='requisicao_realizada', max_length=50, verbose_name='Etapa da adoção'),
        ),
    ]
