# Generated by Django 4.2.2 on 2023-07-04 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_adocao_observacoes_alter_adocao_etapa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adocao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='data_adocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do início da adoção'),
            preserve_default=False,
        ),
    ]
