# Generated by Django 4.2.2 on 2023-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
